version: '3'

services:
  segment-challenge-web:
    image: segment-challenge:${TAG-latest}
    container_name: segment-challenge-web
    restart: always
    environment:
      - MYSQL__HOST=segment-challenge-sql
      - MYSQL__PORT=3306
      - MYSQL__USER=root
      - MYSQL__PASSWORD=${MYSQL__PASSWORD-segmentchallenge}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT-Production}
    volumes:
      - "${API_CONFIG_PATH-./SegmentChallengeWeb/config}:/app/config"
      - "${SITE_CONFIG_PATH-./site-config}:/app/ClientApp/build/config"
    ports:
      - "${HTTP_EXPOSE_PORT-80}:80"
    networks:
      - services
    depends_on:
      - segment-challenge-sql

  segment-challenge-sql:
    image: mysql:5.7
    container_name: segment-challenge-sql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL__PASSWORD-segmentchallenge}
    volumes:
      - segment-challenge-mysql-volume:/var/lib/mysql
    ports:
      - "${MYSQL_EXPOSE_PORT-3306}:3306"
    networks:
      - services

networks:
  services:

volumes:
  segment-challenge-mysql-volume:
    external: true
